name: Issue
description: Normal Issue Template
projects: [ispp-knot/1]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done and why?
      placeholder: Short summary of the task.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Additional context, requirements, or clarifications.
      placeholder: Add any details here.
    validations:
      required: false
